language: python
python:  
  - "3.8"
# command to install dependencies
install:
  - pip install -r ebdjango/requirements.txt

# cd into project dir
before_script:
  - cd ebdjango
# command to run tests
script:
  - pytest test/test.py
  - black --check .
  - flake8 --exclude=migrations --max-line-length=99 .
  - coverage run --source=ebdjango,polls manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: $REGION  
  app: $APP_NAME
  env: $ENVIRONMENT
  bucket_name: $BUCKET_NAME
  on:
    branch: main