language: python
python:  
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

# cd into project dir
before_script:
  - cd ebdjango
# command to run tests
script:
  - pytest test/test.py
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: $REGION  
  app: $APP_NAME
  env: $ENVIRONMENT
  bucket_name: $BUCKET_NAME
  on:
    branch: main